name: Build and Publish Docker Images after push to master branch

on:
  push:
    branches: [main]

jobs:
  build-and-deploy-to-azure:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image and push to Docker Hub and GitHub Container Registry
      run: docker build -t promtail .
