name: Build and Publish Docker Images after push to master branch

on:
  push:
    branches: [master]

jobs:
  build-and-deploy-to-azure:
    runs-on: windows-latest

    steps:
    # Checks out repository so your workflow can access it
    - uses: actions/checkout@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1


    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: windows/amd64
        tags: latest
        push: false

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
